# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.CharField(max_length=30)),
                ('usepass', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=5)),
                ('hobby', models.CharField(max_length=50)),
            ],
        ),
    ]
