# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('users', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsContent',
            fields=[
                ('content_id', models.AutoField(auto_created=True, db_column='content_id', primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('goods', models.ForeignKey(db_column='goods_id', default='', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfor')),
                ('manager', models.ForeignKey(db_column='manager_id', default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ManagerLogin')),
                ('user', models.ForeignKey(db_column='user_id', default='', on_delete=django.db.models.deletion.CASCADE, to='users.UserB')),
            ],
        ),
    ]
