# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserB',
            fields=[
                ('user_id', models.AutoField(auto_created=True, db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('userpass', models.CharField(max_length=40)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
