# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userb',
            name='user_pic',
            field=models.ImageField(max_length=50, null=True, upload_to='media/uploads'),
        ),
    ]
