# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-27 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userb_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('mail_id', models.AutoField(auto_created=True, db_column='mail_id', primary_key=True, serialize=False)),
                ('mail_time', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 27, 14, 36, 55, 652829))),
                ('title', models.CharField(default='', max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='userb',
            old_name='useremail',
            new_name='user_email',
        ),
        migrations.AddField(
            model_name='useremail',
            name='user',
            field=models.ForeignKey(db_column='user_id', default='', on_delete=django.db.models.deletion.CASCADE, to='users.UserB'),
        ),
    ]
