# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
    ]
