# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-13 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('nianji', models.CharField(max_length=50)),
                ('zhuanye', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
