# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(auto_created=True, db_column='stu_id', primary_key=True, serialize=False)),
                ('stuname', models.CharField(default='', max_length=80)),
                ('stusex', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(default='', max_length=20)),
                ('zhuanye', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
