# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='xuehao',
            field=models.CharField(default='', max_length=50),
        ),
    ]
