# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerLogin',
            fields=[
                ('manager_id', models.AutoField(auto_created=True, db_column='manager_id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('userpass', models.CharField(max_length=40)),
                ('nicheng', models.CharField(max_length=40, null=True)),
                ('shop_name', models.CharField(max_length=50, null=True)),
                ('shop_logo', models.ImageField(max_length=50, null=True, upload_to='media/uploads')),
                ('shop_address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
